apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "uaa.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "uaa.fullname" . }}
    spec:
      containers:
      - name: {{ template "uaa.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        env:
        - name: KUBERNETES_ENV
          value: "true"
        - name: UAA_SSL
          value: "true"
        - name: CLOUD_FOUNDRY_CONFIG_PATH
          value: "/usr/local/uaa/config"
        - name: CATALINA_OPTS
          value: "{{ .Values.tomcat.catalinaOpts }}"
        - name: SERVICE_NAME
          value: '{{ template "uaa.fullname" . }}'
        volumeMounts:
        - mountPath: /usr/local/uaa/config
          name: uaa-custom
        - mountPath: /usr/local/uaa/config/tomcat
          name: uaa-tomcat
        - mountPath: /usr/local/uaa/config/ca
          name: uaa-ca
      volumes:
      - name: uaa-custom
        configMap:
          name: {{ template "uaa.fullname" . }}-custom
      - name: uaa-tomcat
        configMap:
          name: {{ template "uaa.fullname" . }}-tomcat
      - name: uaa-ca
        configMap:
          name: {{ template "uaa.fullname" . }}-ca
