apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "uaa.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 60
          env:
            - name: CLOUD_FOUNDRY_CONFIG_PATH
              value: /usr/local/uaa/config
            - name: CATALINA_OPTS
              value: {{ Values.tomcat.catalinaOpts }}
          volumeMounts:
            - mountPath: /usr/local/uaa/config
              name: uaa-custom
            - mountPath: /usr/local/uaa/config/tomcat
              name: uaa-tomcat
      volumes:
        - name: uaa-custom
          configMap:
            name: {{ template "uaa.fullname" . }}-custom
        - name: uaa-tomcat
          configMap:
            name: {{ template "uaa.fullname" . }}-tomcat
