apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "uaa.fullname" . }}-ca
data:
  ca.key: 
    {{ toYaml .Values.uaa.ssl.cakey | indent 4 }}
  ca.crt: 
    {{ toYaml .Values.uaa.ssl.cacert | indent 4 }}
